[tool.poetry]
name = "backend"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pandas = "^3.0.5"
libvoikko = "^4.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
